### ISSUE TITLE
'install awscli' fails when aws is already installed

### ISSUE THREAD

**Issue by sylchamber-qc** [bodsch/ansible-awscli#2]
I tried your role under AlmaLinux9 installed in WSL2 in Windows. First I only called the role as is, and it correctly installed aws cli 2.9.20. Then I upgraded the playbook by specifying the latest version of awscli under `vars`:

```yaml
---
- name: Install aws cli
  hosts: all
  become: true
  vars:
    awscli_version: latest

  roles:
    - bodsch.awscli
```

The playbook failed with:

```text
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["/var/tmp/aws/install"], "delta": "0:00:00.297718", "end": "2023-02-17 16:17:45.819835", "msg": "non-zero return code", "rc": 1, "start": "2023-02-17 16:17:45.522117", "stderr": "Found preexisting AWS CLI installation: /usr/local/aws-cli/v2/current. Please rerun install script with --update flag.", "stderr_lines": ["Found preexisting AWS CLI installation: /usr/local/aws-cli/v2/current. Please rerun install script with --update flag."], "stdout": "", "stdout_lines": []}
```

Your role doesn't seem to handle upgrades. In `/tasks/install.yaml`, line 38, the AWS install script has to be called with the `--update` flag.

I have to say your role is a lot cleaner than my usual approach, which consists of `uri`, `unarchive` and lots of shell commands to compare the latest and current versions. Thanks for your work. I'm still learning ansible, and this is a good example of how I could make my own roles, with tests.

Regards.

**Comment by bodsch** [comment]
My role does allow updates very well.

This involves completely removing the currently installed (old) version and unpacking the new version. An `--update` in the installation call is therefore unnecessary.

There is even a separate molecule test for that.

However, I am not sure if the environment used (WSL and Windows) could be a problem here.

I am currently in the process of reworking the detection of the `latest` version.

Therefore, I will publish a new version shortly.

**Comment by bodsch** [comment]
Please try [1.3.0](https://github.com/bodsch/ansible-awscli/releases/tag/1.3.0)

**Comment by bodsch** [comment]
@sylchamber-qc Have you tested the new version?

Do you still have a problem?

Otherwise I would close the issue.

**Comment by sylchamber-qc** [comment]
Ah sorry, I didn't see the notification. I will try today.

**Comment by bodsch** [comment]
@sylchamber-qc ping

**Comment by bodsch** [comment]
For me it is not comprehensible and there is a separate test workflow for this purpose.
I am closing the issue.
